version: '3.8'
services:
  ghproxy:
    image: Geekertao/ghproxy:latest
    # imageï¼šghcr.io/Geekertao/ghproxy:latest
    container_name: ghproxy
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "45000:45000"
